-- Create "profiles" table
CREATE TABLE "public"."profiles" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" text NOT NULL, PRIMARY KEY ("id"));
-- Create index "idx_profile_name_unique" to table: "profiles"
CREATE UNIQUE INDEX "idx_profile_name_unique" ON "public"."profiles" ("name");
