-- Create "profiles" table
CREATE TABLE "public"."profiles" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "user_id" uuid NOT NULL, "name" text NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "profile_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "idx_profile_name_unique" to table: "profiles"
CREATE UNIQUE INDEX "idx_profile_name_unique" ON "public"."profiles" ("name");
