-- Create "fruits" table
CREATE TABLE "public"."fruits" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" text NOT NULL, "owner_id" uuid NOT NULL DEFAULT gen_random_uuid(), PRIMARY KEY ("id"));
-- Create index "idx_fruits_name_unique" to table: "fruits"
CREATE UNIQUE INDEX "idx_fruits_name_unique" ON "public"."fruits" ("name");
